"""fotos_carregamento_table

Revision ID: 02ce8a2e13c7
Revises: d907663b4c95
Create Date: 2026-07-23 17:34:34.448134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ce8a2e13c7'
down_revision: Union[str, Sequence[str], None] = 'd907663b4c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos_carregamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('romaneio_id', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['romaneio_id'], ['romaneios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('romaneios', 'foto_carregamento_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('romaneios', sa.Column('foto_carregamento_url', sa.VARCHAR(length=500), nullable=True))
    op.drop_table('fotos_carregamento')
    # ### end Alembic commands ###
