"""schema inicial

Revision ID: d907663b4c95
Revises: 
Create Date: 2026-07-21 16:58:22.784982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd907663b4c95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('DESVIO_ROTA', 'NAO_ENTREGA', 'PROBLEMA_ROMANEIO', name='categoriaocorrencia', native_enum=False, length=32), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('exige_foto', sa.Boolean(), nullable=False),
    sa.Column('exige_observacao', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('transportadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transportadoras_cnpj'), 'transportadoras', ['cnpj'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('KAMI_ADMIN', 'TRANSPORTADORA_ADMIN', 'MOTORISTA', name='papel', native_enum=False, length=32), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=True),
    sa.Column('departamento', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('capacidade_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=True)
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.String(length=60), nullable=True),
    sa.Column('acao', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'TRANSICAO_ETAPA', 'RESEQUENCIAMENTO', name='acaoauditoria', native_enum=False, length=32), nullable=False),
    sa.Column('dados_antes', sa.JSON(), nullable=True),
    sa.Column('dados_depois', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=False),
    sa.Column('cnh_categoria', sa.String(length=5), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('romaneios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DEFINICAO_TRANSPORTE', 'CONFERENCIA_LOGISTICA', 'CARREGAMENTO', 'INICIO_ROTA', 'EM_TRANSITO', 'CONCLUIDO', 'ROMANEIO_INCOMPLETO', 'ROMANEIO_COM_PROBLEMA', name='statusromaneio', native_enum=False, length=32), nullable=False),
    sa.Column('origem', sa.Enum('WEBHOOK_TMS', 'MANUAL_TESTE', 'UNO_REPLICA', name='origemromaneio', native_enum=False, length=32), nullable=False),
    sa.Column('tms_referencia_externa', sa.String(length=120), nullable=True),
    sa.Column('tipo_ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('observacao_ocorrencia', sa.Text(), nullable=True),
    sa.Column('qtd_caixas', sa.Integer(), nullable=True),
    sa.Column('qtd_pedidos', sa.Integer(), nullable=True),
    sa.Column('peso_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_veiculo_sugerido', sa.String(length=60), nullable=True),
    sa.Column('data_saida_prevista', sa.DateTime(), nullable=True),
    sa.Column('foto_carregamento_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('conferencia_em', sa.DateTime(), nullable=True),
    sa.Column('carregamento_em', sa.DateTime(), nullable=True),
    sa.Column('inicio_rota_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['tipo_ocorrencia_id'], ['tipos_ocorrencia.id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_romaneios_codigo'), 'romaneios', ['codigo'], unique=True)
    op.create_table('historico_etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('romaneio_id', sa.Integer(), nullable=False),
    sa.Column('etapa_anterior', sa.Enum('DEFINICAO_TRANSPORTE', 'CONFERENCIA_LOGISTICA', 'CARREGAMENTO', 'INICIO_ROTA', 'EM_TRANSITO', 'CONCLUIDO', 'ROMANEIO_INCOMPLETO', 'ROMANEIO_COM_PROBLEMA', name='statusromaneio', native_enum=False, length=32), nullable=True),
    sa.Column('etapa_nova', sa.Enum('DEFINICAO_TRANSPORTE', 'CONFERENCIA_LOGISTICA', 'CARREGAMENTO', 'INICIO_ROTA', 'EM_TRANSITO', 'CONCLUIDO', 'ROMANEIO_INCOMPLETO', 'ROMANEIO_COM_PROBLEMA', name='statusromaneio', native_enum=False, length=32), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('papel_usuario', sa.String(length=32), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['romaneio_id'], ['romaneios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('romaneio_id', sa.Integer(), nullable=False),
    sa.Column('sequencia_original', sa.Integer(), nullable=False),
    sa.Column('sequencia_atual', sa.Integer(), nullable=False),
    sa.Column('status_entrega', sa.Enum('PENDENTE', 'EM_ROTA', 'ENTREGUE', 'NAO_ENTREGUE', 'CANCELADO', name='statusentregapedido', native_enum=False, length=32), nullable=False),
    sa.Column('cliente_nome', sa.String(length=255), nullable=False),
    sa.Column('cliente_endereco', sa.String(length=500), nullable=False),
    sa.Column('cliente_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('cliente_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('cliente_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('cliente_email', sa.String(length=255), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qtd_volumes', sa.Integer(), nullable=True),
    sa.Column('especie_volume', sa.String(length=30), nullable=True),
    sa.Column('dt_entrega_solicitada', sa.Date(), nullable=True),
    sa.Column('tipo_ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('entregue_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['romaneio_id'], ['romaneios.id'], ),
    sa.ForeignKeyConstraint(['tipo_ocorrencia_id'], ['tipos_ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resequenciamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('romaneio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Enum('DIVERGENCIA_MANUAL', 'INSERCAO_PEDIDO', 'AJUSTE_ESPONTANEO', name='origemresequenciamento', native_enum=False, length=32), nullable=False),
    sa.Column('sequencia_antes', sa.JSON(), nullable=False),
    sa.Column('sequencia_depois', sa.JSON(), nullable=False),
    sa.Column('tipo_ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('distancia_estimada_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tempo_estimado_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['romaneio_id'], ['romaneios.id'], ),
    sa.ForeignKeyConstraint(['tipo_ocorrencia_id'], ['tipos_ocorrencia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTREGUE', 'NAO_ENTREGUE', name='tipoeventoentrega', native_enum=False, length=32), nullable=False),
    sa.Column('assinatura_url', sa.String(length=500), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('nome_recebedor', sa.String(length=255), nullable=True),
    sa.Column('geolocalizacao_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geolocalizacao_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('tipo_ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('uno_sync_status', sa.Enum('PENDENTE', 'SINCRONIZADO', 'ERRO', name='unosyncstatus', native_enum=False, length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['tipo_ocorrencia_id'], ['tipos_ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos_entrega')
    op.drop_table('resequenciamentos')
    op.drop_table('pedidos')
    op.drop_table('historico_etapas')
    op.drop_index(op.f('ix_romaneios_codigo'), table_name='romaneios')
    op.drop_table('romaneios')
    op.drop_table('password_reset_tokens')
    op.drop_table('motoristas')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_veiculos_placa'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_transportadoras_cnpj'), table_name='transportadoras')
    op.drop_table('transportadoras')
    op.drop_table('tipos_ocorrencia')
    # ### end Alembic commands ###
